"""
Django settings for projecto project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import dj_database_url


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$h&8^za88o552ww10zggmqie1(ftzxvl2@ojpfxn065(skhd-f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['tubarrio.onrender.com','*']


# Application definition

INSTALLED_APPS = [
    'import_export',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'tubarrio',

]

ASGI_APPLICATION = "projecto.asgi.application"  


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': dj_database_url.parse(
        'postgresql://tubarrio_db_user:u6u8uRFVmbjqP6jx1fcbv2yf28pp5cON@dpg-d74ni2haae7s73bkplcg-a.oregon-postgres.render.com/tubarrio_db'
    )
}

DATABASES['default']['sslmode'] = 'require'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    }
}


JAZZMIN_SETTINGS = {
    # ── Identidad ──────────────────────────────────────────
    "site_title": "TuBarrio Admin",
    "site_header": "TuBarrio",
    "site_brand": "📍 TuBarrio",
    "site_logo": None,  # pon "img/logo.png" si tienes logo en static
    "welcome_sign": "Bienvenido al panel de TuBarrio 🏘️",
    "copyright": "TuBarrio — Loncoche © 2026",

    # ── Íconos del menú lateral ────────────────────────────
    "icons": {
        "auth":                     "fas fa-users-cog",
        "auth.user":                "fas fa-user",
        "auth.Group":               "fas fa-users",
        "tubarrio.Negocio":         "fas fa-store",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # ── Menú lateral ──────────────────────────────────────
    "order_with_respect_to": ["tubarrio", "auth"],

    # ── Navegación superior (links rápidos) ───────────────
    "topmenu_links": [
        {"name": "Inicio",       "url": "admin:index",         "permissions": ["auth.view_user"]},
        {"name": "Ver sitio",    "url": "/",                   "new_window": True},
        {"name": "+ Negocio",    "url": "admin:tubarrio_negocio_add"},
    ],

    # ── Barra de usuario (arriba a la derecha) ────────────
    "usermenu_links": [
        {"name": "Ver sitio",    "url": "/", "new_window": True, "icon": "fas fa-globe"},
    ],

    # ── UI ────────────────────────────────────────────────
    "show_sidebar":             True,
    "navigation_expanded":      True,
    "hide_apps":                [],
    "hide_models":              [],
    "related_modal_active":     True,
    "custom_css":               "css/tubarrio_admin.css",  # tu CSS custom (ver abajo)
    "custom_js":                None,
    "use_google_fonts_cdn":     True,
    "show_ui_builder":          False,   # ponlo True para editar en vivo y copiar config
    "changeform_format":        "horizontal_tabs",  # tabs en el formulario de edición
    "changeform_format_overrides": {
        "auth.user":  "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    # ── Tema base ─────────────────────────────────────────
    "navbar_small_text":        False,
    "footer_small_text":        False,
    "body_small_text":          False,
    "brand_small_text":         False,

    # ── Colores AdminLTE que Jazzmin expone ───────────────
    "brand_colour":             "navbar-dark",
    "accent":                   "accent-warning",      # ámbar para links activos
    "navbar":                   "navbar-dark",
    "no_navbar_border":         True,
    "navbar_fixed":             True,
    "layout_boxed":             False,
    "footer_fixed":             False,
    "sidebar_fixed":            True,
    "sidebar":                  "sidebar-dark-warning", # sidebar oscuro + acento ámbar
    "sidebar_nav_small_text":   False,
    "sidebar_disable_expand":   False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style":False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style":   False,
    "theme":                    "darkly",              # tema oscuro base (Bootstrap)
    "dark_mode_theme":          "darkly",
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
    "actions_sticky_top":       True,
}