# Generated by Django 6.0.3 on 2026-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('mini_market', 'Mini Market'), ('peluqueria', 'Peluquería'), ('comida', 'Comida'), ('otros', 'Otros')], max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('dias_atencion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
