# Generated by Django 6.0.3 on 2026-03-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tubarrio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negocio',
            old_name='sitio_web',
            new_name='facebook',
        ),
    ]
