# Generated by Django 6.0.3 on 2026-03-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubarrio', '0002_rename_sitio_web_negocio_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='ciudad',
            field=models.CharField(blank=True, default='Chile', max_length=100),
        ),
        migrations.AddField(
            model_name='negocio',
            name='comuna',
            field=models.CharField(blank=True, help_text='Comuna donde está ubicado', max_length=100),
        ),
    ]
