# Generated by Django 6.0.3 on 2026-03-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubarrio', '0003_negocio_ciudad_negocio_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='comuna',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
