# Generated by Django 6.0.3 on 2026-03-29 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tubarrio', '0004_alter_negocio_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='descripcion',
        ),
    ]
