# Generated by Django 6.0.3 on 2026-04-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubarrio', '0005_remove_negocio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='tipo',
            field=models.CharField(choices=[('mini_market', 'Mini Market'), ('belleza', 'belleza'), ('comida', 'Comida'), ('panaderia', 'panaderia'), ('servicios', 'servicios'), ('emprendimiento', 'emprendimiento')], max_length=20),
        ),
    ]
