# Generated by Django 6.0.3 on 2026-04-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubarrio', '0006_alter_negocio_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=512, unique=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache geocodificación',
                'verbose_name_plural': 'Caches geocodificación',
            },
        ),
        migrations.AddField(
            model_name='negocio',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='tubarrio_ne_estado_74ca40_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['estado', 'tipo'], name='tubarrio_ne_estado_d45da1_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['tipo'], name='tubarrio_ne_tipo_4af475_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['fecha_creacion'], name='tubarrio_ne_fecha_c_f17715_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['estado', '-fecha_modificacion'], name='tubarrio_ne_estado_435a22_idx'),
        ),
    ]
