# Generated by Django 6.0.3 on 2026-04-18 01:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubarrio', '0007_geocodecache_negocio_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen de negocio',
                'verbose_name_plural': 'Imágenes de negocios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='GeocodeCache',
        ),
        migrations.AddField(
            model_name='negocio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='domicilio',
            field=models.CharField(choices=[('no', 'No, solo en mi local'), ('si', 'Sí, voy al domicilio'), ('ambos', 'Ambas opciones')], default='no', help_text='¿Atendés a domicilio?', max_length=10),
        ),
        migrations.AddField(
            model_name='negocio',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negocio',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='ciudad',
            field=models.CharField(default='Chile', max_length=100),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='tipo',
            field=models.CharField(choices=[('mini_market', 'Mini Market'), ('belleza', 'Belleza'), ('comida', 'Comida'), ('panaderia', 'Panadería'), ('servicios', 'Servicios'), ('emprendimiento', 'Emprendimiento')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['verificado'], name='tubarrio_ne_verific_fff769_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['comuna'], name='tubarrio_ne_comuna_0f1806_idx'),
        ),
        migrations.AddField(
            model_name='imagennegocio',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tubarrio.negocio'),
        ),
    ]
