# Generated by Django 6.0.3 on 2026-04-18 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubarrio', '0008_imagennegocio_delete_geocodecache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('info_incorrecta', 'Información incorrecta'), ('negocio_cerrado', 'Negocio cerrado'), ('ubicacion_mala', 'Ubicación errónea'), ('contenido_malo', 'Contenido inapropiado'), ('duplicado', 'Negocio duplicado'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('email_reporte', models.EmailField(blank=True, max_length=254, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tubarrio.negocio')),
            ],
        ),
    ]
